highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
#paginate: 5
port: 4000
safe: true
url: http://avijit9.github.io/resume
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Avijit Dasgupta's Resume
name: Avijit Dasgupta
email: avijitdasgupta9@gmail.comm
website: avijit9.github.io
github: avijit9
twitter: avijit9d	
tel: +91-8335992569
#google_maps: 'https://www.google.co.uk/maps/place/14+Gowrie+St,+Dundee,+Dundee+City+DD2+1ES'
address: Room No: 140, Bakul Hostel, IIIT Hyderabad
postcode: 5000028
city: Hyderabad
country: India
google_analytics: UA-69291029-

